# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-22 19:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20160822_2025'),
    ]

    operations = [
        migrations.AddField(
            model_name='packages',
            name='recipient_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='packages',
            name='sender_name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
