# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-27 19:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20160927_2112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packages',
            name='deliver_till',
            field=models.DateTimeField(),
        ),
    ]
